/**
 * Per-category SEO keyword sets used in `<meta name="keywords">` for
 * category-index pages.
 *
 * Sourced manually — these are the search queries the product feels
 * relevant for, not a generated list. Keep them generous; Google
 * collapses duplicates at index time.
 */
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Tshirt: [
    'men T-shirts online India', 'buy men T-shirts India', 'T-shirt for men',
    'men polo T-shirts India', 'men round neck T-shirts India', 'men V-neck T-shirts',
    'men cotton T-shirts online', 'best T-shirts for men India', 'men oversized T-shirts India',
    'affordable men T-shirts India', 'men graphic T-shirts India', 'men printed T-shirts India',
    'men T-shirts under 699', 'men T-shirts under 500', 'men plain T-shirts India',
    'men full sleeve T-shirts India', 'men half sleeve T-shirts India',
    'branded T-shirts for men India', 'men T-shirt new arrival India',
    'tshirt for men', 'mens tshirt online', 'boys T-shirt India',
    'drop shoulder T-shirts men', 'streetwear T-shirts India', 'vintage T-shirts men',
    'heavyweight cotton tees', 'baggy T-shirts for men', 'anime T-shirts India',
    'typography printed tees', 'aesthetic T-shirts for men', 'gym T-shirts men India',
    'sports T-shirts men online', 'summer T-shirts men', 'solid color tees men',
    'Myntra T-shirts alternative', 'Ajio T-shirt alternative', 'best T-shirts under 500 India',
    'trendy T-shirts India', 'oversized graphic tees India', 'casual T-shirts men India',
    'curated T-shirts for men India', 'handpicked oversized tees India', 'D2C brand T-shirts India',
    'small brand T-shirts men India', 'no clutter T-shirt shopping India', 'best oversized tee brands India',
  ],
  Shirt: [
    'men shirts online India', 'buy men shirts India', 'shirt for men',
    'men casual shirts online', 'men formal shirts India', 'men cotton shirts online',
    'men linen shirts India', 'men slim fit shirts India', 'men check shirts India',
    'men printed shirts India', 'men plain shirts India', 'men party wear shirts India',
    'affordable men shirts India', 'men shirts under 1000', 'men shirts under 699',
    'branded shirts for men India', 'men half sleeve shirts India',
    'men full sleeve shirts India', 'men denim shirts India',
    'shirt for boys India', 'mens shirt new arrival',
    'Cuban collar shirts men', 'Hawaiian printed shirts India', 'oversized linen shirts',
    'corduroy shirts men', 'Oxford formal shirts India', 'mandarin collar shirts men',
    'flannel check shirts India', 'satin party wear shirts', 'spread collar shirts men',
    'resort wear shirts men', 'textured shirts for men', 'summer shirts men India',
    'curated shirts for men India', 'D2C brand shirts India', 'handpicked linen shirts India',
    'unique printed shirts men India', 'boutique shirt brands men India',
  ],
  Jeans: [
    'men jeans online India', 'buy men jeans India', 'jeans for men',
    'men slim fit jeans India', 'men skinny jeans India', 'men straight fit jeans India',
    'men stretch jeans online', 'best men jeans India', 'men ripped jeans India',
    'men blue jeans online', 'men black jeans India', 'men white jeans India',
    'affordable men jeans India', 'men jeans under 1000', 'men jeans under 699',
    'branded jeans for men India', 'men cargo jeans India', 'men baggy jeans India',
    'denim jeans for men India', 'boys jeans online India',
    'baggy denim jeans men', 'wide leg jeans men India', 'relaxed fit jeans India',
    'bootcut jeans for men', 'vintage wash denim India', 'korean style jeans men',
    'raw denim jeans India', 'stretchable denim jeans men', 'cargo pants for men India',
    'curated jeans for men India', 'Korean style baggy jeans India', 'D2C denim brands India',
    'best baggy jeans brands India', 'unique fit jeans men India',
  ],
  Shoes: [
    'men shoes online India', 'buy men shoes India', 'shoes for men',
    'men sneakers online India', 'men casual shoes India', 'men formal shoes online',
    'men running shoes India', 'men white sneakers India', 'men sports shoes India',
    'best men shoes India', 'affordable men shoes India', 'men shoes under 1000',
    'men shoes under 699', 'men loafers India', 'men boots India',
    'branded shoes for men India', 'men shoes new arrival India',
    'mens footwear online India', 'boys shoes online India',
    'chunky sneakers men India', 'high top sneakers men', 'canvas sneakers India',
    'retro trainers men', 'leather loafers men India', 'Chelsea boots men India',
    'formal Oxford shoes India', 'slip on shoes men', 'athleisure footwear men India',
    'curated sneakers for men India', 'D2C sneaker brands India', 'unique sneaker brands men India',
    'small brand sneakers India', 'trending sneaker drops India',
  ],
  Jacket: [
    'men jackets online India', 'buy men jackets India', 'jacket for men',
    'men bomber jacket India', 'men winter jackets India', 'men denim jacket India',
    'men windbreaker jacket India', 'men puffer jacket India', 'men leather jacket India',
    'best men jackets India', 'affordable men jackets India', 'men jackets under 1000',
    'men lightweight jacket India', 'men rain jacket India',
    'branded jackets for men India', 'boys jacket online India',
    'varsity jackets men India', 'trench coats men', 'fleece jackets India',
    'biker leather jacket men', 'sleeveless gilet jackets men', 'blazer jackets men India',
    'curated jackets for men India', 'D2C jacket brands India', 'unique bomber jacket brands India',
  ],
  Hoodies: [
    'men hoodies online India', 'buy men hoodies India', 'hoodie for men',
    'men pullover hoodies India', 'men zip hoodies India', 'men winter hoodies India',
    'best men hoodies India', 'affordable men hoodies India', 'men hoodies under 699',
    'men oversized hoodie India', 'men printed hoodies India', 'men plain hoodies India',
    'branded hoodies for men India', 'boys hoodies online India',
    'men hoodies under 1000', 'men hoodies new arrival',
    'aesthetic hoodies men', 'fleece pullovers men', 'heavyweight hoodies India',
    'streetwear hoodies men India', 'drop shoulder hoodies men',
    'curated hoodies for men India', 'D2C hoodie brands India', 'unique streetwear brands India',
  ],
  Sweatshirt: [
    'men sweatshirts online India', 'buy men sweatshirts India', 'sweatshirt for men',
    'men crew neck sweatshirts', 'men printed sweatshirts India', 'men plain sweatshirts India',
    'affordable men sweatshirts India', 'men sweatshirts under 699', 'men sweatshirts under 1000',
    'men oversized sweatshirts India', 'branded sweatshirts for men India',
    'vintage sweatshirts men', 'fleece sweatshirts men India', 'graphic sweatshirts men',
  ],
  Sweater: [
    'men sweaters online India', 'buy men sweaters India', 'sweater for men',
    'men woollen sweaters India', 'men winter sweaters India', 'men knit sweaters online',
    'affordable men sweaters India', 'men sweaters under 1000', 'men cardigan India',
    'branded sweaters for men India',
    'turtleneck sweaters men India', 'mock neck sweaters men', 'knit pullovers men',
  ],
  Trackpants: [
    'men track pants online India', 'buy men track pants India', 'track pants for men',
    'men joggers online India', 'men gym track pants India', 'men cotton track pants India',
    'affordable men joggers India', 'men joggers under 699', 'men track pants under 500',
    'men slim fit joggers India', 'branded track pants for men India',
    'boys joggers online India', 'men lower online India',
    'cargo joggers men India', 'fleece joggers men', 'loungewear pants men',
    'open bottom track pants men', 'athleisure track pants India',
  ],
  'Mens Accessories': [
    'men accessories online India', 'buy men accessories India', 'accessories for men',
    'men belts online India', 'men wallets online India', 'men sunglasses India',
    'men caps online India', 'men watches India', 'men bracelets India',
    'affordable men accessories India', 'branded accessories for men India',
    'bucket hats men India', 'UV protection sunglasses men', 'silver chains for men',
    'leather belts men India', 'ankle socks men',
  ],
  Innerwear: [
    'men innerwear online India', 'buy men innerwear India', 'innerwear for men',
    'men briefs online India', 'men boxers online India', 'men trunks online India',
    'men gym innerwear India', 'affordable men underwear India', 'men vests online India',
    'branded innerwear for men India', 'men innerwear under 500',
    'boxer briefs men India', 'seamless underwear men', 'cotton boxers men',
  ],
  Perfume: [
    'men perfume online India', 'buy men perfume India', 'perfume for men',
    'men cologne India', 'best men fragrance India', 'affordable men perfume India',
    'men body spray India', 'men deodorant India', 'men perfume under 500',
    'branded perfume for men India', 'long lasting perfume for men India',
    'eau de parfum men India', 'woody perfume men', 'pocket perfume men India',
  ],
  Traditional: [
    'men ethnic wear online India', 'buy men kurta online India', 'kurta for men',
    'men traditional wear India', 'men kurta pyjama India', 'men sherwani online India',
    'men festive wear India', 'men wedding wear India', 'men pathani suit India',
    'branded kurta for men India', 'men ethnic wear under 1000',
    'short kurta for men India', 'Nehru jacket set men', 'chikankari kurta men',
  ],
  'Body Care': [
    'men body care products India', 'men grooming products online India', 'body care for men',
    'men moisturizer India', 'men face wash online India', 'affordable men body care India',
    'men skincare products India', 'men body lotion India', 'men grooming kit India',
    'best body care for men India',
    'men beard oil India', 'men sunscreen SPF 50', 'charcoal face wash men',
  ],
  'Daily Essentials': [
    'men daily essentials online India', 'men grooming essentials India', 'daily essentials for men',
    'men everyday products India', 'affordable men essentials India',
    'men hygiene products India', 'men lifestyle products India',
    'men everyday grooming India', 'men lip balm India', 'men hair wax India',
  ],
};

/** Fallback keywords for any unmapped category. */
export const FALLBACK_KEYWORDS = (label: string): string[] => [
  `men ${label.toLowerCase()} online India`,
  `buy ${label.toLowerCase()} India`,
  `best ${label.toLowerCase()} for men India`,
  `affordable ${label.toLowerCase()} men India`,
  `trending ${label.toLowerCase()} India`,
  `curated ${label.toLowerCase()} for men India`,
  `D2C brand ${label.toLowerCase()} India`,
  `unique ${label.toLowerCase()} brands men India`,
];
